### ISSUE TITLE
Top 5 list order issue

### ISSUE THREAD

**Issue by codelano** [kcc-community/kcc-discover-frontend#1]
When you navigate to https://discover.kcc.io/ Top 5 projects on KCC are listed.
Currently top 5 items are listed randomly, let say 
![image](https://user-images.githubusercontent.com/15995240/135838080-a5029f81-83cb-48fb-8c01-dda4144a13d0.png)
 Example, KuAcorn projects has 11 review with 5 starts rating, but it's not in top 5 project.

Please fix sorting or explain on what criteria it's listed if list is correct.

**Comment by TroubleSeven** [comment]
hi, there is no problem with this rank since it was ranked by the tvl data. It's the top 5 tvl ranking.
